version: '3.8'
services:
  arma3:
    build: .
    image: ghcr.io/marsniper27/arma3server/arma3server:latest
    platform: linux/amd64
    container_name: arma3
    network_mode: host
    volumes:
      - '/mnt/HDDs/arma3/missions:/arma3/mpmissions'
      - '/mnt/HDDs/arma3/configs:/arma3/configs'
      - '/mnt/HDDs/arma3/mods:/arma3/mods'
      - '/mnt/HDDs/arma3/servermods:/arma3/servermods'
    env_file: stack.env
    restart: unless-stopped
    ports:
      - 2302-2306/udp
